### ISSUE TITLE
Ability to support multiple value entries in a config snippet

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#10]
In some cases the user may need to add multiple interfaces, zones, tags, etc. to a part of the configuration. Currently this would require 'micro templates' that only add a single item and the user would have to manually re-run this skillet to add multiple values.

Other option would be the ability to add a comma-separated or similar input to add multiple members into the configuration element.

Best example is adding multiple zones or tags to the same security rule.

**Comment by nembery** [comment]
added new 'list' type in 'dev'. Please give this a test and let me know if this solves this use case

**Comment by scotchoaf** [comment]
I need to test. Adam B has tested with a sample GP skillet for a few values:
https://github.com/adambaumeister/gpskillet/blob/65f7262e2cc4caad7c3b25e1b8a4db03c456c0b4/templates/panos/snippets/.meta-cnc.yaml#L76

I need to create a test skillet to validate
