### ISSUE TITLE
type hint fqdn_or_ip doesn't filter for FQDN

### ISSUE THREAD

**Issue by rrega** [PaloAltoNetworks/panhandler#101]
Regex looks for hostname only (not very useful for enterprise or cloud environments)

## Possible solution
Replace current regex on validators.py line 18 to
        hostname_re = r'(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$)$'
Instead of current 
        hostname_re = r'[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])$'

**Comment by rrega** [comment]
validators.py with new regex validated on my environment
[validators.zip](https://github.com/PaloAltoNetworks/panhandler/files/3772367/validators.zip)

**Comment by nembery** [comment]
fixed via commit 
b89c86f
