### ISSUE TITLE
use of 'when' in variables section to allow panHandler to hide-show web form fields

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#118]
include the same model for a when condition in the variables section that if True shows a web form. False hides the field. If not specific, default is True to show. 

The web form will dynamically update if a pulldown or field text is updated so some dynamic capability in the UI.

This additional can alleviate much of the web form clutter with unused fields and not require the use of workflows for simple skillet loading

**Comment by scotchoaf** [comment]
here is sample javascript code with comments. haven't tested inside cnc html template yet but looks fairly straightforward. comments added in the script and div areas where jinja bits would be used

key points:
. special case class added in the div if a when is used; used to hide/show groups of fields
. script block added to check a dropdown change and hide/show the fields based on class name


`
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    
// guessing a jinja conditional used in the script section of the html template file
// one for each 'if field.when is True' input
// the #var name is the associated var id value (existing today)
// the div.variable is the class name used below as dv and the ref field var name
// conditional pulled from the when statment eg. when PhyIntfType == 'static'
// simple translation to parse the when and use jinja vars in the script below

    var checkPattern = function () {
      if ($('#PhyIntfType').val() == 'static') {
        $('div.dvPhyIntfType').show();
      }
      else $('div.dvPhyIntfType').hide();
    }

// this is used to cover setting the state on the field load or refresh
// likely browser dependent if sets back to default state vs remembers cached inputs
    $(document).ready(function(){
      // add event handler
      $('#PhyIntfType').on('change', checkPattern);
      // call to adjust div
      checkPattern();
    });

</script>

<span>phy interface type</span>
<select id="PhyIntfType">
    <option value="dhcp">dhcp</option>
    <option value="static">static</option>
</select>
<hr />
<!––
guessing here is a jinja conditonal in cnc html file
if field.when with when added to a var statement
eg. when PhyIntfType == 'static' --> the values used above in the script
when var_label == value and var_label is associated field
class could be set to dv_var_label where dv prefix stands for dropdown value
-->

<div class="dvPhyIntfType" style="display: none">
    ip address:
    <input type="text" id="txtPhyIntfAddress" />
</div>
<div class="dvPhyIntfType" style="display: none">
    netmask:
    <input type="text" id="txtPhyIntfNetmask" />
</div>
`

**Comment by nembery** [comment]
implemented via commit: 0222d34099869bf412c5768deb44cf0c13920b30
