### ISSUE TITLE
Panhandler Updates (Auto and Manual)

### ISSUE THREAD

**Issue by mghazzi** [PaloAltoNetworks/panhandler#12]
Panhandler should phone home to github every 24hrs for updates, and have an internal button that says "check now" , this phone home functionality should provide new code, new repos, and new skillets.

**Comment by punisherVX** [comment]
I would add to this that the default can be 24hrs (or whatever) but the setting itself should be configurable so that it will check as per the user's needs.

**Comment by scotchoaf** [comment]
assuming this is for panhandler application updates for the container and will open another issue specific to the repo updates

**Comment by nembery** [comment]
updating the container automatically will require the new provisioner container to be present. However, we do now have a check to notify the user if their version is out-of-date and should be updated, along with instructions on how to do that. ref commit:  887d27c9d388bf4712d02505c771d612c8bd4d4c

Closing for now until we determine architecture of container management service
