### ISSUE TITLE
First stage workflow option to 'always use same target' and bypass each stage form view to load config

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#127]
This is specific to the panos/panorama workflow skillets where each workflow stage has a form view to choose the ip/user/password for api configuration.

As an alternative, allow for a checkbox var in the workflow that would only prompt for this info once and then just jump to each workflow stage. 

other inclusion would be 'commit at the end' so that each stage loads and then include a final commit

**Comment by scotchoaf** [comment]
after additional usage ideal may be a no commit/fast commit/full commit option in the workflow. In some cases great to quickly step through while online validation checks require a commit to validate against the running config

**Comment by nembery** [comment]
can use hidden vars to bypass this
