### ISSUE TITLE
panHandler repo refresh says already updated when new updates are in the repo

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#129]
Have periodic issues where a repo update to latest does not update. It tries and I get the 'already updated' message.

Current work around is to pick another branch then switch back to the desired branch. then the update happens.

**Comment by nembery** [comment]
verified this is working as expected. Updates will only appear if the upstream changes happen in the same branch as you have checked out. Switching to the upstream branch with the changes will show them after the checkout, without having to do another update.
updates to the same branch are caught correctly as well.
