### ISSUE TITLE
Add kubectl cli tool to the build

### ISSUE THREAD

**Issue by dommyjc** [PaloAltoNetworks/panhandler#155]
Please add the kubectl cli tool to the build so that we can also manage kubernetes clusters (https://kubernetes.io/docs/tasks/tools/install-kubectl/)

**Comment by nembery** [comment]
@dommyjc I just today built a develop version of panhandler that uses dockerized terraform containers. I have added kubectl to the default 0.11 and 0.12 images. 

images are being built via gitlab-ci and 0.11 is available by default in panhandler:dev. If you want to use 0.12, you can set a label in your skillet with key: `terraform_image`. The value is the name / tag of a docker image that has terraform as it's entry point. 

This command will update panhandler to the latest develop version:

```bash

 curl -k -s -L http://bit.ly/34kXVEn | bash

```

default terraform images are being built and hosted here: https://gitlab.com/panw-gse/as/terraform_tools.

testing 0.12 based images can be done by added the following label to your skillet:

```yaml

labels:
  terraform_image: registry.gitlab.com/panw-gse/as/terraform_tools:0.12

```

We can add additional tags / terraform versions / included libraries pretty easily by creating a new branch in gitlab.

Please take a look and let me know if this works
