### ISSUE TITLE
Show specific API error in the panhandler GUI

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#16]
Using the xml example, if an issue with a snippet load the GUI only shows a generic 'skillet doesn't load' error message. The user has to go into the docker/system logs to see which xml bit doesn't load and error details.

Request is to display more detailed error messages in the onscreen pop-up specific to the API issues.

**Comment by nembery** [comment]
completed as part of 2.0 sprint
