### ISSUE TITLE
fw api-key using cached credential instead of updated env user/password

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#17]
The xml / panos configuration was started with admin/admin default credentials. This appears to be cached in panhandler. If a new user is added in the fw and this user/password is configured in panhandler it appears to work. However, per the fw logs panhandler is actually still using the admin/admin credentials.

When the admin password is changed in the fw, an API errors show up for invalid credentials and logs show an auth-fail event.

Expectation is that this cache is removed and the env or pop-up target user/password info is used instead

**Comment by nembery** [comment]
initial fix in commit: 703559b2. will leave open until tested and confirmed

**Comment by nembery** [comment]
confirmed as fixed
