### ISSUE TITLE
toggle_hint not hiding the hidden list labels or added list rows

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#184]
Running skillet:
https://github.com/scotchoaf/ping-test/blob/develop/ping_test_2/.meta-cnc.yaml

Designed to hide the list if file type selected and will hide the file upload if list selected

Toggle not hiding elements as expected

## Describe the bug

When choosing on option the 'hidden' option field label is still shown. The label and field should both be hidden.

For a list when adding additional rows, the added rows still appear although this variable should be hidden.

panHandler version: Version: 3.1-DEV 2020-04-03T13:00:38

## Steps to reproduce

Label showing:

Select file or list and the hidden label will still be shown

List row showing:

Set type to list
Create a list variable with > 1 entries
Set type to file

**Comment by nembery** [comment]
fixed via commit: 275603cfe0d9b3b012e43add5696a55ae456dc58
