### ISSUE TITLE
python3 skillet not generating output from subprocess.run

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#185]
## Describe the bug

https://github.com/scotchoaf/ping-test/blob/a87ff6cb5025f810cb710d4081e6a457261374fa/ping_test_2/ping_test.py#L44

This script runs ping and generates rtt output. When running locally in python 3.6 or 3.7 no issues and rtt values are generated.

When run in the panHandler container, it hits the error for response=None showing:
Error processing pings. Check inputs

I can ping the URLs from the terminal exec console with successful results

## Expected behavior

should have a running output of url ping rtt results

## Steps to reproduce

load ping-test into panHandler using the develop branch. Run with list or file input.

## Your Environment

- Version used: Version: 3.1-DEV 2020-04-03T13:00:38 
- Link to your project: https://github.com/scotchoaf/ping-test/tree/develop

**Comment by nembery** [comment]
verified output is OK, this particular problem is due to running the script as non-root user
