### ISSUE TITLE
Running -v command doesn't create persistent environment

### ISSUE THREAD

**Issue by chm0t** [PaloAltoNetworks/panhandler#19]
After running the -v command `docker run -t -p 9999:80 -v ~/.pan_cnc:/root/.pan_cnc paloaltonetworks/panhandler`from [this page](https://panhandler.readthedocs.io/en/latest/running.html#using-an-alternate-tcp-port), the environment does not seem to persist. Adding 1) a description to the readthedocs page on the command, and 2) instructions on how to validate that the directory has been created would be extremely helpful.

**Comment by nembery** [comment]
updated docs to reflect this
