### ISSUE TITLE
support password checks / dual entry in password form fields

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#21]
When using type_hint = password you can't see the text entered. For this type_hint, panhandler should show two password entry fields and check that the entries are the same. Otherwise users may enter passwords incorrectly. This could be a major issue when loading configs with only a single admin superuser w/out the default password.

**Comment by nembery** [comment]
may need to show a password or possibly add a 'verify' attribute then add a second password entry to the generate_dynamic_form field and then form_valid should check that they match
