### ISSUE TITLE
requirements.txt and cnc/requirements.txt break pip 

### ISSUE THREAD

**Issue by punisherVX** [PaloAltoNetworks/panhandler#22]
When installing panhandler from source, running the initial pip install -r requirements.txt breaks pip because pip is in the requirements file and it upgrades the system pip if the user doesn't use virtualenvs.  This also happens when running the cnc/requirements.txt install too if you get that far.  

An example of how to fix, if this does happen, is here:
https://stackoverflow.com/questions/49836676/error-after-upgrading-pip-cannot-import-name-main

Need to fix the documentation to show how to use virtualenvs, remove the pip upgrades from the requirements.txt files or, preferably, force the use of our container so that we don't spend an inordinate amount of time un-horking everything and get the user working.

**Comment by nembery** [comment]
removed pip from requirements and also pipenv. Will also remove instructions on building the app and put a big ole warning that only the container is supported
