### ISSUE TITLE
Add version to panhandler

### ISSUE THREAD

**Issue by punisherVX** [PaloAltoNetworks/panhandler#24]
Need a way to determine the version "number" (or name or whatever) a user is running.  This will allow for easier support if someone is out of rev and running into a problem.  
This can be via the panhandler dropdown or even just in the header of the app (towards the right probably) but should be easy to find.

**Comment by kevwal1** [comment]
Be good to see version number if Log (on system startup is OK) and from the GUI

**Comment by nembery** [comment]
implemented with commit: a70aa50e85b48f277abaf37075cf6a846ad7cee2 

Will now auto generate a timestamp version from CI/CD system and show up in docker containers
