### ISSUE TITLE
Inconsistent error handling for bad IP or credentials

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#28]
error handling seems inconsistent. in some cases I get a generic 'Could not login to PAN-OS' and some times a red box with the proper error message. also seeing some cases where wrong ip/credentials + backup=checked gives a browser level error, cant perform backup. I also did a clear cache (check the port # in the docs?) and getting the older generic message

When I did see the red box, it does capture bad IP or credentials as expected

**Comment by nembery** [comment]
completed with 2.1
