### ISSUE TITLE
View any yaml errors when importing a new skillet repo

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#29]
When importing a skillet that has incorrect yaml parameters, no errors are shown on screen and only in the log output. If a user doesn't know to look for the metadata/collection values at time of import, they may be looking for collections/skillets that won't be shown in the collection view.

At a minimum there should be a user warning if no collection or metadata label is found since likely a bad yaml file and unusable skillet.

**Comment by scotchoaf** [comment]
The ideal would be a simple error notice for key expected items. New users likely have no clue what a collection, label, or future elements would be. Yes the builder should have resolved this but over time panhandler may be ahead of older skillets that may fail to load or run. Just ran into this loading my KibanaSkillets and luckily knew the collection was missing. Want to avoid any burden on a user if the app knows what it needs. Also gets to potential for a message/link for a user to open an issue from the repo page to get it fixed. So yes, a debug would be great for the builder but may not be the end solution for a standard user.

**Comment by nembery** [comment]
implemented in commit: 16c05dce29229d3294c01694e07cd5d68950d6dc
new image building now, and will be ready for test soon
