### ISSUE TITLE
variable override option or auto-use defaults

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#3]
In the case of MSSP configuration there are 2 types of variables:

(1) MSSP specific (syslog, DNS, NTP,...)
(2) customer specific (device name, trust-side IP address)

Need the app to only have the customer specific variables shown in the web forms and the MSSP specific in a conf or override file. Currently you have to list ALL variables in the metadata file.

In relation, if you use 'extends' you need to pick up default variables values when the baseline is MSSP specific values not provided in the web form data. best example is the iron-skillet baseline with a gold add-on. The system would only present the gold set of variables resulting in processing errors for the iron-skillet variables not entered into a form.

**Comment by nembery** [comment]
Solved by use of Environments
