### ISSUE TITLE
need capture of any commit errors

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#31]
even through a config can load successfully,  the commit can fail. panhandler has no view of this stage other than a commit submitted. need to determine if the user has to check the fw locally or have the error condition appear in panhandler

**Comment by nembery** [comment]
best we can do is add a force_sync option that would wait for commit to finish and report any errors

**Comment by nembery** [comment]
how about changing commit checkbox into a select with the following options:
- no commit - push config but do not commit
- queue commit - push config a  do not wait for commit
- Synchronous commit - push config and wait for commit to complete, gathering any errors

**Comment by nembery** [comment]
implemented via: https://github.com/PaloAltoNetworks/panhandler/commit/3f2f28c5c772e8f51919a9053d60a94fb9818f46
