### ISSUE TITLE
yaml type_hint for hybrid IP-FQDN fields

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#32]
many fields may be set to type_hint ip but the system will allow for an FQDN. panhandler gives a web form validation error since the FQDN is not an actual IP address format. Instead of generic text, have a type_hint fqdn that supports both ip address and fqdn formats

**Comment by nembery** [comment]
addressed in commit #6b8a348ad55ffc88fc2c90740156f2488c887584 

However, we need to think this through a bit as we can't know if a user really wants an IP but mistyped it, or if she really wants a hostname afternall

1.2.3.asdfasdf could be valid hostname but not a valid IP address so basically anything validates except for special characters like @#$@#$@#...

**Comment by nembery** [comment]
addressed this completely: fa7d43129c5eb6ddde2ba3d0aefd274f6cb1199c

also added docs to dev
