### ISSUE TITLE
not seeing perform commit or backup checkboxes for type panorama

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#34]
for panos skillets there is an option for commit and backup. Not seeing this for the panorama IronSkillet configuration. Only the fw web form data and Submit

**Comment by nembery** [comment]
panos only for 2.1 release, Just requires some additional testing in dev for panorama and then can add to 2.2 in next sprint

**Comment by nembery** [comment]
can we confirm API calls are the same for panos and panorama? Initial implementation in cnc library here: https://github.com/PaloAltoNetworks/pan-cnc/commit/1652d00a1b598aa39c03c5e438fb3542ea5ab79c

**Comment by nembery** [comment]
completed
