### ISSUE TITLE
type_hint ip_address to support cidr notation

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#36]
the current ip_address type hint appears to only support simple ipv4/v6 addresses. looking for this type hint to also support cidr notation (eg. 1.1.1.1/24) to avoid using type_hint = text and requirement to update existing skillets that are failing web form validation

**Comment by nembery** [comment]
Completed and documented as of commit: 6a4ae8e8972b3853ab00878ed80faa856295840e
