### ISSUE TITLE
Check for repo updates from panhandler

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#38]
ability to have panhandler check for updates re: the imported skillets. Current model requires going into each repo and updating to latest. If manual, could be an 'update all' top level button. Second level would be scheduled auto updates with time interval set by the user.

**Comment by nembery** [comment]
stage 1 complete with a button in the repos list page to 'Update All Repositories'. Needs more testing though to catch errors with import errors but good enough to push to develop. Ref commit: 08d991ec1f588d99b50e6290c94e68c3fcc84e09

**Comment by nembery** [comment]
Calling this one good to go
