### ISSUE TITLE
Support private repo import

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#4]
When sandboxing new skillets or working with pre-release code want to have a way to import a private repo into panhandler with ssh. Currently spins and times out. Then when trying to add additional repos, errors out with stderr: 'fatal: bad revision {branch name}

**Comment by nembery** [comment]
You can do this today, however, you must mount your .ssh dir inside the container for ssh based private repos to work. The following command works (assuming your default ssh key has access to the private repo in github)

`docker run -p 8081:80 -v ~/.ssh:/root/.ssh paloaltonetworks/panhandler`

note the `-v ~/.ssh:/root/.ssh` bit there

**Comment by nembery** [comment]
there seems to be a bug though when adding a repo fails and subsequent ones also then fail, so leaving open to track that for sure

**Comment by nembery** [comment]
fixed issues with importing failures and subsequent failures

https://github.com/PaloAltoNetworks/pan-cnc/commit/7d257d2c4e2ff44da630cac0819804decbf8a432
