### ISSUE TITLE
Confirm correct skillets & repos loaded in 2.1

### ISSUE THREAD

**Issue by kevwal1** [PaloAltoNetworks/panhandler#41]
We need to make sure that the correct repos for Skillets are loaded into the *new* version of panhandler.

- seems like the IronSkillet/HomeGateway skillets have issues with the IP Address (/xx I think) text checking in the UI
- the GP skillets may still be pointing to scotchoaf repo instead of paloalto repo

We should be able to verify all of the repos and repost 2.1  quietly.

Concern here is that Stevens is about to announce PanHandler to the WW SE list in an update and we need a seemless first experience.

**Comment by Konrad1984** [comment]
develop@{1day}...develop

**Comment by nembery** [comment]
Updated and waiting for review before closing

**Comment by nembery** [comment]
completed for 2.2 GA
