### ISSUE TITLE
Ability to render a bootstrap.xml text file from multiple skillets

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#44]
For bootstrap based deployments, only a single skillet such as IronSkillet, is used to create a bootstrap.xml file. If any modifications are needed for the bootstrap, the user has to manually edit the IronSkillet config file.

Instead, much like to loading a series of skillets over the API that merge into the config file, the user could use a set of skillets with a single output xml configuration.

IronSkillet currently has a similar tool that rolls up a set of snippets into a complete xml config file. The same model could be useful but would be extended across skillets. In some cases a static workflow yet in other cases allowing the user to ad hoc select skillets for their bootstrap.xml configuration.

Also want to use existing pan-os templates without the need to recreate as type = template for text render. The app has to know this is a config file build and instead of an api call is just using the variables and xml load info from the metadata file.

**Comment by nembery** [comment]
essentially we need a template builder workflow. Something like: Choose base config -> Add skillet -> customize variables for that skillet -> add another skillet -> customize that skillet -> repeat 2 and 3 ... -> render as template (or push to device?) . @scotchoaf

**Comment by scotchoaf** [comment]
I think so. Confirming this isn't a predetermined template builder workflow - that is another option. This is more of a user ad hoc workflow to randomly select skillets that merge into one monolithic config file. If doing API-based configuration I keep popping into collections menus and can choose to load IronSkillet, mssp gold, and globalprotect. These merge into the firewall candidate config. Instead I'm pushing to a local pseudo candidate config that eventually renders one xml file output.

Example use case is to have IronSkillet Day 1, a BPA upgraded skillet on top of IronSkillet, and public cloud elements from a 3rd skillet. this generates an output file to bootstrap or import into the firewall w/out API access.
