### ISSUE TITLE
dev branch: Removal of .pan_cnc directory causes stack trace of no directory found

### ISSUE THREAD

**Issue by punisherVX** [PaloAltoNetworks/panhandler#51]
You would think this would be highly unlikely, but it does happen.  Forced this to happen here, but it should catch the error.

**To reproduce:**
Start panhandler
Move ~/.pan_cnc to ~/pan_cnc (or whatevs)
Navigate to Panhandler --> Skillet Repositories
BLAMMO - stack trace:

Request Method: | GET
-- | --
http://localhost:9999/panhandler/repos
2.2
FileNotFoundError
[Errno 2] No such file or directory: '/root/.pan_cnc/panhandler/repositories'
/usr/local/lib/python3.6/pathlib.py in wrapped, line 387
/usr/local/bin/python3
3.6.8
['/usr/local/lib/python3.6/site-packages/git/ext/gitdb',  '/app/cnc',  '/app/src',  '/app/cnc',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages',  '/usr/local/lib/python3.6/site-packages/gitdb/ext/smmap']
Thu, 30 May 2019 23:23:55 +0000

**Comment by nembery** [comment]
Should be fixed with commit: c47742da1727fb24e1f9980952e67536872ff474

**Comment by punisherVX** [comment]
This is fixed in dev.  Closing after release of 2.2
