### ISSUE TITLE
fqdn_or_ip type hint does not allow fqdn

### ISSUE THREAD

**Issue by silliker-paloaltonetworks** [PaloAltoNetworks/panhandler#58]
Version: 2.2 2019-06-20T23:05:15

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: fqdn_or_ip

Example inputs failing validation:
customer.com
domain.customer.com
system.domain.customer.com

Example inputs successfully validating:
customer

**Comment by nembery** [comment]
fixed via commit: 8df0cb22e2fee32512522901866c6666cd1fa37b

Thanks for the BR
