### ISSUE TITLE
Celery should not run as root

### ISSUE THREAD

**Issue by stealthllama** [PaloAltoNetworks/panhandler#60]
I receive the following warning when running panhandler:

`docker run -p 9991:80 paloaltonetworks/panhandler:dev
/usr/local/lib/python3.6/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is absolutely not recommended!`

We should be able to run this container with a uid other than root.

Reference: [https://stackoverflow.com/questions/53037874/docker-celery-tells-me-not-to-run-as-root-but-once-i-dont-i-lack-permission](https://stackoverflow.com/questions/53037874/docker-celery-tells-me-not-to-run-as-root-but-once-i-dont-i-lack-permission)

**Comment by nembery** [comment]
Fixed in dev with commit: b8ae3354848b614706ee4772fe40925a4f936920

will wait until further testing to close
