### ISSUE TITLE
documentation: update grep command to find ALL vars in a string line

### ISSUE THREAD

**Issue by scotchoaf** [PaloAltoNetworks/panhandler#91]
The panhandler docs show a grep shortcut to find variables in the directory:

https://panhandler.readthedocs.io/en/master/metadata_configuration.html#ensuring-all-variables-are-defined

This appears to only do a 'first match' in each text row instead of 'all match'. This is an issue for set commands that often have multiple vars per row

**Comment by nembery** [comment]
after spending entirely too longing working this out: documented via perl in commit: 4f9db87c
